apiVersion: apps/v1
kind: Deployment
metadata:
  name: emails
  labels:
    app: emails
spec:
  replicas: ${EMAILS_REPLICAS}
  selector:
    matchLabels:
      app: emails
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: emails
    spec:
      imagePullSecrets:
        - name: docker-creds
      initContainers:
        - name: prestart-emails
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          command: ["bash", "/app/scripts/prestart.sh"]
          envFrom:
            - configMapRef:
                name: emails-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: NATS_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: EMAILS_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SMTP_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

      containers:
        - name: emails
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2048Mi"
          envFrom:
            - configMapRef:
                name: emails-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: NATS_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: EMAILS_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SMTP_PASSWORD
          readinessProbe:
            httpGet:
              path: /utils/health
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /utils/health
              port: 8000
            periodSeconds: 10
            failureThreshold: 3
      restartPolicy: Always
