apiVersion: v1
kind: ConfigMap
metadata:
  name: emails-env
data:
  # Postgres
  POSTGRES_CONNECTION_SCHEME: postgresql
  POSTGRES_SERVER: microservices-pg-cluster-rw-pgbouncer.${DATABASE_NAMESPACE}.svc
  POSTGRES_READ_SERVER: microservices-pg-cluster-ro-pgbouncer.${DATABASE_NAMESPACE}.svc
  POSTGRES_PORT: "5432"
  POSTGRES_USER: appuser
  POSTGRES_DB: Emails
  # SMTP
  SMTP_HOST: smtp.resend.com
  SMTP_USER: resend
  SMTP_TLS: "True"
  SMTP_PORT: "465"
  EMAILS_FROM_EMAIL: no-reply@microservices.com
  EMAILS_FROM_NAME: Microservices
