apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emails
spec:
  ingressClassName: traefik
  rules:
    - host: api.${DOMAIN}
      http:
        paths:
          - path: /emails
            pathType: Prefix
            backend:
              service:
                name: emails
                port:
                  number: 8000
