apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-worker
  labels:
    app: users-worker
spec:
  replicas: ${USERS_WORKER_REPLICAS}
  selector:
    matchLabels:
      app: users-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: users-worker
    spec:
      imagePullSecrets:
        - name: docker-creds
      initContainers:
        - name: prestart-users-worker
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          command: ["bash", "/app/scripts/prestart.sh"]
          envFrom:
            - configMapRef:
                name: users-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: NATS_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: USERS_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
      containers:
        - name: users-worker
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          command:
            ["taskiq", "worker", "src.tasks:broker", "--log-level", "INFO"]
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: users-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: NATS_URL
              valueFrom:
                secretKeyRef:
                  name: nats-secrets
                  key: NATS_URL
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: USERS_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
      restartPolicy: Always
