global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "services"
    static_configs:
      - targets:
          - auth:9000
          - auth-scheduler:9000
          - auth-worker:9000
          - emails:9000
          - emails-scheduler:9000
          - emails-worker:9000
          - users:9000
          - users-scheduler:9000
          - users-worker:9000
