apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-worker
  labels:
    app: auth-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auth-worker
    spec:
      initContainers:
        - name: prestart-auth-worker
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          command: ["bash", "/app/scripts/prestart.sh"]
          envFrom:
            - configMapRef:
                name: auth-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: AUTH_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
      containers:
        - name: auth-worker
          imagePullPolicy: IfNotPresent
          image: ${IMAGE}
          command:
            ["taskiq", "worker", "src.tasks:broker", "--log-level", "INFO"]
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          envFrom:
            - configMapRef:
                name: auth-env
          env:
            - name: ENVIRONMENT
              value: ${ENVIRONMENT}
            - name: DOMAIN
              value: ${DOMAIN}
            - name: PROJECT_NAME
              value: ${PROJECT_NAME}
            - name: FRONTEND_HOST
              value: ${FRONTEND_HOST}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: MYSQL_PASSWORD
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_PASSWORD
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: redis-secrets
                  key: AUTH_REDIS_URL
            - name: ROOT_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: ROOT_USER_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: SECRET_KEY
      restartPolicy: Always
