apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: emails
  namespace: default

spec:
  rules:
    - host: emails.blndly.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emails
                port:
                  number: 8000
    - host: www.emails.blndly.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: emails
                port:
                  number: 8000
